/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import coursemanagement.dbcon;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;



/**
 *
 * @author Nirmadha
 */
public class CourseMainPage extends javax.swing.JFrame {
    /**
     * 
     * 
     
     */
    
    Connection conn = null;
    String fac;
    String co;
    
    public CourseMainPage() {
        initComponents();
        conn = dbcon.connect();
        loadfacList();
        loadcoursList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void loadfacList() {
        try{
            
           
           String sql = "SELECT `faculty` FROM `faculty_list`";
                          
           Statement state = conn.createStatement();
           
           ResultSet r = state.executeQuery(sql);
           
           while(r.next()){
               String fac = r.getString("faculty");
               facultySelectCombo2.addItem(fac);           
           }
           
        }
        
        catch (SQLException e){
            System.out.println(e);
 
        } 
    }
    
    private void loadcoursList() {
        try{
            
           //Class.forName("com.mysql.jdbc.Driver");
           
           String sql = "SELECT `coursename` FROM `course_list`";
                          
           Statement state = conn.createStatement();
           
           ResultSet r = state.executeQuery(sql);
           
           while(r.next()){
               String fac = r.getString("coursename");
               courseSelectCombo1.addItem(fac);           
           }
           
        }
        
        catch (SQLException e){
            System.out.println(e);
 
        }
    }
        
    private String getfaculty(){
        
        fac = (String) facultySelectCombo2.getSelectedItem();
        
        return fac;
        
    }
    
    private String getcourse(){
        
        co = (String) courseSelectCombo1.getSelectedItem();
        
        return co;
        
    }
  
   
  
    private void commonError(){
        JFrame jFrame2 = new JFrame();
        JOptionPane.showMessageDialog(jFrame2, "Redirect Unsuccessful");
    }
        
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header1 = new javax.swing.JLabel();
        courseSelect = new javax.swing.JLabel();
        courseSelectCombo1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        facultySelectCombo2 = new javax.swing.JComboBox<>();
        MainButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Header1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Header1.setText("Tutora");

        courseSelect.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        courseSelect.setText("Select your Field of Research");

        courseSelectCombo1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        courseSelectCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select" }));
        courseSelectCombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseSelectCombo1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Select your Faculty");

        facultySelectCombo2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        facultySelectCombo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select" }));
        facultySelectCombo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                facultySelectCombo2MouseEntered(evt);
            }
        });
        facultySelectCombo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultySelectCombo2ActionPerformed(evt);
            }
        });

        MainButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MainButton1.setText("Go to Course");
        MainButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(Header1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(MainButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(facultySelectCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(courseSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(courseSelectCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Header1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(facultySelectCombo2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(courseSelectCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(MainButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void facultySelectCombo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultySelectCombo2ActionPerformed
        
    }//GEN-LAST:event_facultySelectCombo2ActionPerformed

    private void courseSelectCombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseSelectCombo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseSelectCombo1ActionPerformed

    private void facultySelectCombo2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facultySelectCombo2MouseEntered
     
    }//GEN-LAST:event_facultySelectCombo2MouseEntered

    private void MainButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainButton1ActionPerformed
        
        String fac = getfaculty();
        String co = getcourse();
        
        System.out.println(fac);
        System.out.println(fac.getClass().getSimpleName());
        System.out.println(co);
        System.out.println(co.getClass().getSimpleName());
        
        
        /*if (fac == null || fac == "Please Select"){
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "You have to Select a Faculty from Drop Down List");
        }
        
        else if (co == null || co == "Please Select"){
            JFrame jFrame1 = new JFrame();
            JOptionPane.showMessageDialog(jFrame1, "You have to Select a Course from Drop Down List");
        }*/
        
        
        if (fac.equals("IT")  && co.equals("Information Technology") ){
            
            System.out.println("fac check success");
            commonError();
        }
        
        else if (fac.equals("IT") && co.equals("Software Engineering")){
            
            System.out.println("fac check success");
            softwareEng se = new softwareEng();
                
            se.setVisible(true);
            this.dispose();
            
        }
        
        else if (fac.equals("IT") && co.equals("Artificial Intelligence")){
            
            System.out.println("fac check success");
            
            ArtificialIntelligence arti = new ArtificialIntelligence();
                
            arti.setVisible(true);
            this.dispose();
            
        }
        
        else if (fac.equals("Medicine") && co.equals("Neuro Science")){
            
            System.out.println("fac check success");
            
            Neuroscience nuro = new Neuroscience();
                        
            nuro.setVisible(true);
            this.dispose();
            
        }
        
        else if (fac.equals("Medicine") && co.equals("Child Psychology")){
            
            System.out.println("fac check success");
            
            ChildPsychology chpy = new ChildPsychology();
                
            chpy.setVisible(true);
            this.dispose();
            
        }
        
        else if (fac.equals("Engineering") && co.equals("Chemical Enginnering")){
            
            System.out.println("fac check success");
            
            commonError();
            
        }
        
        else if (fac.equals("Engineering") && co.equals("Civil Engineering")){
            
            System.out.println("fac check success");
            
            CivilEng civileng = new CivilEng();
                
            civileng.setVisible(true);
            this.dispose();
            
        }
        
        else if (fac.equals("Engineering") && co.equals("Mechatronics")){
            
            System.out.println("fac check success");
            
            Mechatronics mecha = new Mechatronics();
                
            mecha.setVisible(true);
            this.dispose();
            
        }
        
        else if (fac.equals("Business") && co.equals("Business Administration")){
            
            System.out.println("fac check success");
            
            commonError();
            
        }
        
        
            
        
        else if (fac == null || fac == "Please Select" && co == null || co == "Please Select"){
            
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "You have to Select Faculty and Course from Drop Down Lists");
        }
            
               
    }//GEN-LAST:event_MainButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        
       
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CourseMainPage().setVisible(true);
                                           
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Header1;
    private javax.swing.JButton MainButton1;
    private javax.swing.JLabel courseSelect;
    private javax.swing.JComboBox<String> courseSelectCombo1;
    private javax.swing.JComboBox<String> facultySelectCombo2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
